language: python
python:
  - 3.7
  - 3.8
script:
  - python3 -m unittest discover tests
  - pip3 install coverage
  - coverage run --source common setup.py test
  - coverage xml 
  - pip3 install codacy-coverage
  - python-codacy-coverage -r coverage.xml

